### ISSUE TITLE
Use v3 API for Twitch Emotes

### ISSUE THREAD

**Issue by andrewlin16** [andrewlin16/duckbot#23]
Currently using v2 API for Twitch Emotes which has been deprecated, switch to v3.

https://www.twitchemotes.com/apidocs

**Comment by afzalarsalan** [comment]
LUL

**Comment by andrewlin16** [comment]
This sort of broke the LUL emote, by the way. What I believe to be the sequence of events:

1. LUL added as BTTV emote (fine)
2. At some point, Twitch Emotes v2 API gets deprecated (no updates), has v3 API
3. LUL gets added as an official Twitch emote, probably added to v3 API but not v2 API
4. LUL gets turned into LuL on the BTTV side (broken)
